### ISSUE TITLE
feature -> zambrano-1 -> voting -> Priority voting

### ISSUE THREAD

**Issue by pabpercab1** [EGC-zambrano/decide-part-zambrano#14]
**Is your feature request related to a problem? Please describe.**
Currently, users lack the ability to prioritize or rank items when voting on questions, which limits the clarity and specificity of preferences in certain scenarios.

**Describe the solution you'd like**
I propose implementing an option that allows users to prioritize their votes by ranking the items within a question. This feature would enable users to assign a hierarchy or order to their choices, providing more nuanced feedback and enhancing the decision-making process.

**Describe alternatives you've considered**
One alternative could be using the existent simple voting system without ranking. However, this might not capture the relative importance or preference among multiple items in a question.

**Additional context**
The inclusion of a priority vote feature could significantly enhance the platform's usability, especially in cases where users need to express preferences among multiple options. This feature could streamline decision-making processes and improve the accuracy of gauging user preferences.

**Comment by MartaInes** [comment]
While doing the test I realized that the part of the multi voting in the file voting/models.py was erased, which make the test previously done for this type of voting to fail. This should be fixed as soon as possible.

**Comment by pabpercab1** [comment]
Now should be solve.
