### ISSUE TITLE
feature -> zambrano-1 -> voting -> White voting

### ISSUE THREAD

**Issue by FelixoGudiel** [EGC-zambrano/decide-part-zambrano#22]
Is your feature request related to a problem? Please describe.
There is no current way of voting in blank.

Describe the solution you'd like
Create the possiblity to vote in blank for each question.

Describe alternatives you've considered
Add the voting option "In Blank" for desired questions.

Additional context
Before the frontend of this feature is done, the frontend of the feature "multioption voting #17" should be done.

**Comment by samrodman** [comment]
I took charge of the issue.
