### ISSUE TITLE
feature -> zambrano-2 -> Authentication -> login-github

### ISSUE THREAD

**Issue by Marchabar** [EGC-zambrano/decide-part-zambrano#33]
**Is your feature request related to a problem? Please describe.**
It is not bound to a problem, it is for integrating github  authentication through the platform

**Describe the solution you'd like**
A github  authentication method that works

**Describe alternatives you've considered**
I have considered no other alternatives

**Additional context**
No additional context

**Comment by Marchabar** [comment]
Hey, who want to test this functionality?. The implementation is already done.

For the github login to work you need the following:

We need to install social auth, then:
```
pip install -r requirements.txt
``` 
```
python decide/manage.py makemigrations
python decide/manage.py migrate
```
In your .env add the following (ask Marchabar for the values of the variables and do not share them):
```
GITHUB_KEY=github_key_Marchabar
GITHUB_SECRET=github_secret_Marchabar
```
If you did all of this correctly, it should work.
The GitHub login button is in the login page under the google login.
Now you are ready to do the tests.

**Comment by JaviGarc1a** [comment]
Hi, I can test for your functionality.

**Comment by Marchabar** [comment]
> Hi, I can test for your functionality.

Great!
