### ISSUE TITLE
bug -> zambrano-1 -> Voting -> Boolean voting

### ISSUE THREAD

**Issue by pabpercab1** [EGC-zambrano/decide-part-zambrano#48]
**Describe the bug**
When attempting to add more than two QuestionOptions to a boolean voting configuration, the system encounters a 500 Internal Server Error. It should also be checked whether questions with only one option are adequately addressed the same way as the ones with more than 2.

**To Reproduce**
Steps to reproduce the behaviour:
1.   Navigate to the Question section.
2.   Create a new question, selecting Boolean voting as the question type.
3.   Add more than two options to the question.
4.   Click on save.

**Expected behaviour**
To enhance user experience and improve error handling, consider providing a more appropriate HTTP error code such as 400, 401, or 405. This adjustment would ensure a clearer indication of the issue to the user while allowing the application to handle the error more effectively.

**Possible solution (optional)**
Revise the error handling related to exceeding the allowed number of options for Boolean voting. Modify the ValueError handling to manage out-of-range options more gracefully. This may involve implementing specific error codes (e.g., 400 Bad Request) and appropriate error messages to guide users in creating questions within the allowed parameters.

**Comment by TunixR** [comment]
This problem should not result in a new bug report since the original boolean voting feature is not closed. Please adhere to the issue tracking and management policies.
