### ISSUE TITLE
bug -> zambrano-1 -> Voting -> Boolean voting with white voting

### ISSUE THREAD

**Issue by pabpercab1** [EGC-zambrano/decide-part-zambrano#55]
**Describe the bug**
When attempting to create boolean voting with the white voting option, it does not appear to work because of the current implementation of boolean voting.

**To Reproduce**
Steps to reproduce the behaviour:

1. Navigate to the Question section.
2. Create a new question, selecting Boolean voting as the question type and check VoteBlanck.
3. Create the question and a vote.
4. See how only appear the boolean voting and not the white voting.

**Expected behaviour**
It should appear as an option with the white voting option.

**Comment by TunixR** [comment]
This is not a live issue, the pull request regarding Boolean Voting is still in progress, the white voting issue was closed prior to this feature being complete. If this issue appears in a stable branch then it will be opened, but the issue corresponding to this feature is still not closed, meaning that all discussion regarding broken states should be handled either in the corresponding feature issue or in the PR. Please adhere to the issue tracking and management policies
